board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from todos import views
#from . import views

app_name= 'todos'

urlpatterns = [
    path('', views.index, name="index"),

    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),

    path('add/', views.add, name="add"),
    
    path('<int:id>/delete/', views.delete, name="delete"),

    path('<int:id>/update/', views.update, name="update"),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=50)
    content =  models.TextField()
    due_date =  models.DateField()
    author =   models.CharField(max_length=50)

todos/views.py
from django.shortcuts import render, redirect
from todos.models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos' : todos,
    }
    return render(request, 'index.html',context)

def new(request):
    return render(request, 'new.html')

def create(request):
    author = request.POST.get('author')
    title = request.POST.get('title')
    content = request.POST.get('content')
    due_date = request.POST.get('due-date')

    # todo = Todo()
    # todo.title = title
    # todo.save()

    # todo = Todo(title=title, content=content)
    # todo.save()

    todo = Todo.objects.create(
        author=author, 
        title=title, 
        content=content, 
        due_date=due_date
        )
    
    return redirect('todos:index')

def delete(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()

    return redirect('todos:index')

def add(request):
    if request.method == "POST":
        author = request.POST.get('author')
        title = request.POST.get('title')
        content = request.POST.get('content')
        due_date = request.POST.get('due-date')

        todo = Todo.objects.create(
        author=author, 
        title=title, 
        content=content, 
        due_date=due_date
        )
    
        return redirect('todos:index')

    else:
        return render(request, 'add.html')

def update(request, id):
    todo = Todo.objects.get(id=id)
    if request.method == "POST":
        #todo = Todo.objects.get(id=id)
        author = request.POST.get('author')
        title = request.POST.get('title')
        content = request.POST.get('content')
        due_date = request.POST.get('due-date')

        todo.author = author
        todo.title = title
        todo.content = content
        todo.due_date = due_date
        todo.save()

        return redirect('todos:index')

    else:
        #todo = Todo.objects.get(id=id)
        context = {
            'todo' : todo,
        }
        return render(request, 'update.html',context)

todos/templates/add.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        작성자 : <input type="text" name="author">
        제목 : <input type="text" name="title">
        내용 : <input type="text" name="content">
        마감일 : <input type="date" name="due-date">
        <input type="submit" value="저장">
    </form>
{% endblock %}

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo</title>
</head>
<body>
    <a href="{% url 'todos:index' %}">전체글 보기</a>
    <a href="{% url 'todos:new' %}">할 일 추가</a>
    <a href="{% url 'todos:add' %}">할 일 추가(합쳐진 코드)</a>

    {% block body %}
    {% endblock %}
</body>
</html>

todos/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <h1>index</h1>
    {% for todo in todos %}
    <h5>{{todo.author}}-{{todo.title}}/{{todo.due_date}}</h5>
    <a href="{% url 'todos:delete' todo.id %}">삭제</a>
    <a href="{% url 'todos:update' todo.id %}">수정</a>
    {% endfor %}
{% endblock %}

todos/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'todos:create' %}" method="post">
        {% csrf_token %}
        작성자 : <input type="text" name="author">
        제목 : <input type="text" name="title">
        내용 : <input type="text" name="content">
        마감일 : <input type="date" name="due-date">
        <input type="submit" value="저장">
    </form>
{% endblock %}

todos/templates/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        작성자 : <input type="text" name="author" value="{{todo.author}}">
        제목 : <input type="text" name="title" value="{{todo.title}}">
        내용 : <input type="text" name="content" value="{{todo.content}}">
        마감일 : <input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
        <input type="submit" value="저장">
    </form>
{% endblock %}